CREATE TABLE IF NOT EXISTS programs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  programtitle VARCHAR(255) NULL,
  subtitle VARCHAR(255) NULL,
  totalcost DOUBLE(20,2) NULL DEFAULT 0,
  discount_price DOUBLE(20,2) NULL DEFAULT 0,
  duration VARCHAR(255) NULL,
  requirement LONGTEXT NULL,
  discription LONGTEXT NULL,
  outcome LONGTEXT NULL,
  numberofcourses INT NULL DEFAULT 0,
  allcourses LONGTEXT NULL,
  faqs LONGTEXT NULL,
  payment_plan LONGTEXT NULL,
  total_enrolled INT NOT NULL DEFAULT 0,
  user_id INT NULL,
  image VARCHAR(255) NULL,
  icon VARCHAR(255) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  featured TINYINT NOT NULL DEFAULT 0,
  review_id INT NULL,
  lms_id TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_plans (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  amount DOUBLE(20,2) NULL DEFAULT 0,
  planed_amount DOUBLE(20,2) NULL DEFAULT 0,
  parent_id BIGINT UNSIGNED NULL,
  type VARCHAR(50) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  sdate DATE NULL,
  cdate DATE NULL,
  edate DATE NULL,
  no_of_students INT NULL DEFAULT 0,
  lms_id TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_plan_details (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  amount DOUBLE(20,2) NULL DEFAULT 0,
  sdate DATE NULL,
  edate DATE NULL,
  type VARCHAR(50) NULL,
  payment_plan_id BIGINT UNSIGNED NULL,
  lms_id TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS how_programs_work (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NULL,
  subtitle VARCHAR(255) NULL,
  text TEXT NULL,
  image VARCHAR(255) NULL,
  seq_no INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  lms_id TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS student_program_payment_plans (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  amount DOUBLE(20,2) NULL DEFAULT 0,
  sdate DATE NULL,
  edate DATE NULL,
  type VARCHAR(50) NULL,
  program_id BIGINT UNSIGNED NULL,
  plan_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  pay_status VARCHAR(50) NULL DEFAULT 'pay',
  lms_id TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
